config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # defaults to dashboard
  root :to => 'dashboard#dashboard_h'

  get 'fligths/search' => 'flights#search', as: :search_flights
  post 'flights/do_search' => "flights#do_search", as: :do_search_fligths
  get 'flights/:id/add_people' => 'flights#add_people', as: :flight_add_people
  post 'flights/:id/add_person/:person_id' => 'flights#add_person', as: :flight_add_person
  post 'flights/:id/remove_person/:person_id' => 'flights#remove_person', as: :flight_remove_person
  get 'flights/:id/finish' => 'flights#finish', as: :flight_finish
  
  get 'users/search' => 'users#search', as: :search_users
  post 'users/do_search' => "users#do_search", as: :do_search_users
  
  get 'planes/search' => 'planes#search', as: :search_planes
  post 'planes/do_search' => "planes#do_search", as: :do_search_planes

  get 'services/search' => 'services#search', as: :search_services
  post 'services/do_search' => "services#do_search", as: :do_search_services

  get 'flight_types/search' => 'flight_types#search', as: :search_flight_types
  post 'flight_types/do_search' => "flight_types#do_search", as: :do_search_flight_types

  get 'habilitation/:id' => 'pilot_habilitations#habilitation', as: :habilitation
  
  get 'users/recover' => 'users#recover', as: :recover
  post 'users/do_recover' => 'users#do_recover', as: :do_recover
    
  resources :planes
  resources :people
  resources :users
  resources :flights
  resources :ticket_flights
  resources :ticket_members
  resources :flight_types
  resources :services
  resources :pilot_habilitations
  resources :lists
  put 'flights/:id/deshabilitar' => 'flights#deshabilitar', as: :flight_deshabilitar
  put 'flights/:id/activar' => 'flights#activar', as: :flight_activar

  put 'ticket_flights/:id/deshabilitar' => 'ticket_flights#deshabilitar', as: :ticket_flights_deshabilitar
  put 'ticket_flights/:id/activar' => 'ticket_flights#activar', as: :ticket_flights_activar
  put 'ticket_flights/:id/finish' => 'ticket_flights#finish', as: :ticket_flights_finish

  put 'ticket_members/:id/finish' => 'ticket_members#finish', as: :ticket_members_finish
  
  get 'information/top_time' => 'lists#top_time', as: :top_time
  get 'information/people_with_debt' => 'lists#debt', as: :debt
  get 'information/monthly(/:year/:month)' => 'lists#monthly', as: :monthly



  # view routes
  get '/widgets' => 'widgets#index'
  get '/documentation' => 'documentation#index'

  get 'dashboard/dashboard_v1'
  get 'dashboard/dashboard_v2'
  get 'dashboard/dashboard_v3'
  get 'dashboard/dashboard_h'
  get 'elements/button'
  get 'elements/notification'
  get 'elements/spinner'
  get 'elements/animation'
  get 'elements/dropdown'
  get 'elements/nestable'
  get 'elements/sortable'
  get 'elements/panel'
  get 'elements/portlet'
  get 'elements/grid'
  get 'elements/gridmasonry'
  get 'elements/typography'
  get 'elements/fonticons'
  get 'elements/weathericons'
  get 'elements/colors'
  get 'elements/buttons'
  get 'elements/notifications'
  get 'elements/carousel'
  get 'forms/standard'
  get 'forms/extended'
  get 'forms/validation'
  get 'forms/wizard'
  get 'forms/upload'
  get 'forms/xeditable'
  get 'multilevel/level1'
  get 'multilevel/level3'
  get 'charts/flot'
  get 'charts/radial'
  get 'charts/chartjs'
  get 'charts/chartist'
  get 'charts/morris'
  get 'charts/rickshaw'
  get 'tables/standard'
  get 'tables/extended'
  get 'tables/datatable'
  get 'tables/jqgrid'
  get 'maps/google'
  get 'maps/vector'
  get 'extras/mailbox'
  get 'extras/timeline'
  get 'extras/calendar'
  get 'extras/invoice'
  get 'extras/search'
  get 'extras/todo'
  get 'extras/profile'
  get 'blog/blog'
  get 'blog/blog_post'
  get 'blog/blog_articles'
  get 'blog/blog_article_view'
  get 'ecommerce/ecommerce_orders'
  get 'ecommerce/ecommerce_order_view'
  get 'ecommerce/ecommerce_products'
  get 'ecommerce/ecommerce_product_view'
  get 'forum/forum_categories'
  get 'forum/forum_topics'
  get 'forum/forum_discussion'
  get 'pages/login'
  get 'pages/register'
  get 'pages/recover'
  get 'pages/lock'
  get 'pages/template'
  get 'pages/notfound'

  # api routes
  get '/api/documentation' => 'api#documentation'
  get '/api/datatable' => 'api#datatable'
  get '/api/jqgrid' => 'api#jqgrid'
  get '/api/jqgridtree' => 'api#jqgridtree'
  get '/api/i18n/:locale' => 'api#i18n'
  post '/api/xeditable' => 'api#xeditable'
  get '/api/xeditable-groups' => 'api#xeditablegroups'

  # the rest goes to root
  get '*path' => redirect('/')
end

app/models/ticket_member.rb
class TicketMember < ActiveRecord::Base
  belongs_to :person

  enum status: [ :Activo, :Deshabilitado, :Pago ]

  def self.custom_delete(ticket_member)
    ticket_member.status = 1
    return ticket_member.save
  end

  def self.search(query)
    return TicketMember.joins(:person).where('upper(people.id_number) like ? or upper(people.name) like ? or upper(people.surname) like ? or upper(ticket_members.date) = ?', "%#{query.upcase}%", "%#{query.upcase}%", "%#{query.upcase}%", "#{query}")
  end

end

app/controllers/ticket_members_controller.rb
class TicketMembersController < ApplicationController

layout 'application-h'

  def index
    #lleva vista
    if !params[:q].nil?
      @ticket_members = TicketMember.search(params[:q])
    else
      @ticket_members = TicketMember.all
    end
  end


  def create
   @ticket_member = TicketMember.new (ticket_members_params)
   if @ticket_member.save
    flash[:success] = 'El ticket del socio creado correctamente.'
    redirect_to ticket_members_url(@ticket_member)
   else
    flash[:error] = 'Errores evitaron que se grabara el ticket del socio.'
    render 'new'
   end
  end

  def new
    #lleva vista
    @ticket_member = TicketMember.new
  end

  def edit
  #lleva vista
  @ticket_member = TicketMember.find(params[:id])
  end

  def show
  #lleva vista
  @ticket_member = TicketMember.find(params[:id])
  end

  def update
  @ticket_member = TicketMember.find(params[:id])
  if @ticket_member.update_attributes(ticket_members_params)
  flash[:success] = 'El ticket del socio actualizado correctamente.'
  redirect_to ticket_members_url(@ticket_member.id)
  else
  flash[:error] = 'Errores evitaron que se grabara el ticket del socio.'
  render 'edit'
  end
  end
  
  def finish
   @ticket = TicketMember.find(params[:id]) 
   @ticket.status = 2
   if @ticket.save
      redirect_to ticket_members_url()
   
    else
      flash[:error] = 'Errores evitaron que se finalizara la factura vuelo.'
      redirect_to ticket_members_url()
    end
  
  end

  def destroy
  Rails.logger.info "Eliminando el ticket del socio."
    @ticket_member = TicketMember.find(params[:id])
    if TicketMember.custom_delete(@ticket_member)
    flash[:success] = 'El ticket del socio deshabilitado correctamente.'
    redirect_to ticket_members_url
  else
  flash[:error] = 'Errores evitaron que se deshabilitara el ticket del socio.'
  render 'show'
  end    
  end

  private
  # Using a private method to encapsulate the permissible parameters is
  # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    def ticket_members_params
    params.require(:ticket_member).permit(:person_id, :price, :status, :date)
    end

end

app/helpers/ticket_member_helper.rb
module TicketMemberHelper
end

app/views/ticket_members/_form.html.erb
<h3>Crear nueva ticket de socio
   <small>Llene el formulario con los datos necesarios para crear un ticket de socio</small>
</h3>
<!-- START panel-->
<div class="panel panel-default">
   <div class="panel-heading">Crear nuevo ticket</div>
   <div class="panel-body">
      <%= form_for ticket_member, html: {class: 'form-horizontal'} do |f| %>
         <div class="form-group">
            <label class="col-lg-2 control-label">Socio</label>
            <div class="col-lg-10">
             <%= f.select :person_id, options_from_collection_for_select(Person.where(guest: true), :id, :complete_name_id_number), required:'required' %>
            </div>
         </div>
         <div class="form-group">
            <label class="col-lg-2 control-label">Fecha</label>
            <div class="col-lg-10">
              <%= f.date_select :date, :order => [:day, :month, :year] %>
             </div>
         </div>
         <div class="form-group">
            <label class="col-lg-2 control-label">Precio</label>
            <div class="col-lg-10">
              <%= f.text_field :price, placeholder: 'Precio', class: 'form-control', required:'required' %>
             </div>
         </div>
         <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
         		<%= f.submit 'Guardar Cobranza', class: 'btn btn-success'%>
         		<% if ticket_member.new_record? %>
         		  <%= link_to 'Volver', ticket_members_path, class: 'btn btn-danger' %>
         		<% else %>
         		  <%= link_to 'Volver', ticket_members_path(@ticket_member), class: 'btn btn-danger' %>
         		<% end %>
         	</div>
         </div>
      <% end %>
   </div>
</div>

app/views/ticket_members/edit.html.erb
<h1>Editar el ticket del socio</h1>

<%= render partial: 'form',locals: {ticket_member: @ticket_member } %>

app/views/ticket_members/index.html.erb
<div class="row">
   <div class="col-lg-12">
      <h3>Cuotas socios
         <small>Listado de cuotas de socios</small>
      </h3>

      <%= form_tag(ticket_members_path, method: 'get') do  %>
        <%= text_field_tag :q,'',  placeholder: 'Busque por cedula, nombre, apellido y fecha', :size => 42 %>
        <%= button_tag 'Buscar', type: 'submit',  class: 'btn btn-info btn-lg' %>
      <% end %>

   </div>
</div>
<!-- START row-->
<div class="row">
   <div class="col-lg-12">
      <!-- START panel-->
      <div class="panel panel-default">
         <div class="panel-body">
            <!-- START table-responsive-->
            <div class="table-responsive">
               <table class="table table-striped table-bordered table-hover">
                  <thead>
                     <tr>
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Cedula</th>
                        <th>Fecha</th>
                        <th>Precio</th>
                        <th>Estado</th>
                     </tr>
                  </thead>
                  <tbody>
                  <% @ticket_members.each do |ticket|%>
                     <tr>
                        <td><a href="<%= ticket_member_path(ticket) %>">Ver</a>
                        <% if ticket.Activo? %>
                        /
                        
                        <%= link_to 'Pagar Mes', ticket_members_finish_path(ticket.id), method: :put, data: { confirm: "Esta seguro?" } %>
                        <% end %>
                        
                        </td>
                        <td><%= ticket.person.name %></td>
                        <td><%= ticket.person.surname %></td>
                        <td><%= ticket.person.id_number %></td>
                        <td><%= ticket.date %></td>
                        <td><%= ticket.price %></td>
                        <td><%= ticket.status %></td>
                     </tr>
                  <% end %>
                  </tbody>
               </table>
            </div>
            <!-- END table-responsive-->

            <div class='row actions' style='margin-top: 30px'>
              <div class='col-xs-10'>
                  <%= link_to 'Nuevo', new_ticket_member_path, class: 'btn btn-success' %>
                  <%= link_to 'Volver', root_path, class: 'btn btn-default' %>
              </div>
            </div>
         </div>
      </div>
      <!-- END panel-->
   </div>
</div>

app/views/ticket_members/new.html.erb
<h1>Guardar tickets de socios</h1>

<%= render partial: 'form', locals: {ticket_member: @ticket_member} %>

app/views/ticket_members/show.html.erb
<h3>Detalles de
   <small><%= @ticket_member.person_id %></small>
</h3>

<div class="panel">
   <div class="panel-heading">Detalles del talon de cobranza</div>
   <table id="plane" style="clear: both" class="table table-bordered table-striped">
      <tbody>
         <tr>
            <td width="35%">Nombre</td>
            <td width="65%"><strong><%= @ticket_member.person.name %></strong>
            </td>
         </tr>
         <tr>
            <td width="35%">Apellido</td>
            <td width="65%"><strong><%= @ticket_member.person.surname %></strong>
            </td>
         </tr>
         <tr>
            <td width="35%">Cedula</td>
            <td width="65%"><strong><%= @ticket_member.person.id_number %></strong>
            </td>
         </tr>
         <tr>
            <td width="35%">Fecha</td>
            <td width="65%"><strong><%= @ticket_member.date %></strong>
            </td>
         </tr>
         <tr>
            <td width="35%">Precio</td>
            <td width="65%"><strong><%= @ticket_member.price %></strong>
            </td>
         </tr>
         <tr>
            <td width="35%">Estado</td>
            <td width="65%"><strong><%= @ticket_member.status %></strong>
            </td>
         </tr>
      </tbody>
   </table>
</div>

<a href="<%= edit_ticket_member_path(@ticket_member) %>" class='btn btn-success'>Modificar</a>

<%= link_to 'Eliminar', @ticket_member, method: :delete, data: {confirm: "Estas seguro que quiere eliminar?"}, class: 'btn btn-danger' %>
<%= link_to 'Volver', ticket_members_path, class: 'btn btn-default' %>