config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # defaults to dashboard
  root :to => 'dashboard#dashboard_h'

  get 'fligths/search' => 'flights#search', as: :search_flights
  post 'flights/do_search' => "flights#do_search", as: :do_search_fligths
  get 'flights/:id/add_people' => 'flights#add_people', as: :flight_add_people
  post 'flights/:id/add_person/:person_id' => 'flights#add_person', as: :flight_add_person
  post 'flights/:id/remove_person/:person_id' => 'flights#remove_person', as: :flight_remove_person
  get 'flights/:id/finish' => 'flights#finish', as: :flight_finish
  
  get 'users/search' => 'users#search', as: :search_users
  post 'users/do_search' => "users#do_search", as: :do_search_users
  
  get 'planes/search' => 'planes#search', as: :search_planes
  post 'planes/do_search' => "planes#do_search", as: :do_search_planes

  get 'services/search' => 'services#search', as: :search_services
  post 'services/do_search' => "services#do_search", as: :do_search_services

  get 'flight_types/search' => 'flight_types#search', as: :search_flight_types
  post 'flight_types/do_search' => "flight_types#do_search", as: :do_search_flight_types

  get 'habilitation/:id' => 'pilot_habilitations#habilitation', as: :habilitation
  
  get 'users/recover' => 'users#recover', as: :recover
  post 'users/do_recover' => 'users#do_recover', as: :do_recover
    
  resources :planes
  resources :people
  resources :users
  resources :flights
  resources :ticket_flights
  resources :ticket_members
  resources :flight_types
  resources :services
  resources :pilot_habilitations
  resources :lists
  put 'flights/:id/deshabilitar' => 'flights#deshabilitar', as: :flight_deshabilitar
  put 'flights/:id/activar' => 'flights#activar', as: :flight_activar

  put 'ticket_flights/:id/deshabilitar' => 'ticket_flights#deshabilitar', as: :ticket_flights_deshabilitar
  put 'ticket_flights/:id/activar' => 'ticket_flights#activar', as: :ticket_flights_activar
  put 'ticket_flights/:id/finish' => 'ticket_flights#finish', as: :ticket_flights_finish

  put 'ticket_members/:id/finish' => 'ticket_members#finish', as: :ticket_members_finish
  
  get 'information/top_time' => 'lists#top_time', as: :top_time
  get 'information/people_with_debt' => 'lists#debt', as: :debt
  get 'information/monthly(/:year/:month)' => 'lists#monthly', as: :monthly



  # view routes
  get '/widgets' => 'widgets#index'
  get '/documentation' => 'documentation#index'

  get 'dashboard/dashboard_v1'
  get 'dashboard/dashboard_v2'
  get 'dashboard/dashboard_v3'
  get 'dashboard/dashboard_h'
  get 'elements/button'
  get 'elements/notification'
  get 'elements/spinner'
  get 'elements/animation'
  get 'elements/dropdown'
  get 'elements/nestable'
  get 'elements/sortable'
  get 'elements/panel'
  get 'elements/portlet'
  get 'elements/grid'
  get 'elements/gridmasonry'
  get 'elements/typography'
  get 'elements/fonticons'
  get 'elements/weathericons'
  get 'elements/colors'
  get 'elements/buttons'
  get 'elements/notifications'
  get 'elements/carousel'
  get 'forms/standard'
  get 'forms/extended'
  get 'forms/validation'
  get 'forms/wizard'
  get 'forms/upload'
  get 'forms/xeditable'
  get 'multilevel/level1'
  get 'multilevel/level3'
  get 'charts/flot'
  get 'charts/radial'
  get 'charts/chartjs'
  get 'charts/chartist'
  get 'charts/morris'
  get 'charts/rickshaw'
  get 'tables/standard'
  get 'tables/extended'
  get 'tables/datatable'
  get 'tables/jqgrid'
  get 'maps/google'
  get 'maps/vector'
  get 'extras/mailbox'
  get 'extras/timeline'
  get 'extras/calendar'
  get 'extras/invoice'
  get 'extras/search'
  get 'extras/todo'
  get 'extras/profile'
  get 'blog/blog'
  get 'blog/blog_post'
  get 'blog/blog_articles'
  get 'blog/blog_article_view'
  get 'ecommerce/ecommerce_orders'
  get 'ecommerce/ecommerce_order_view'
  get 'ecommerce/ecommerce_products'
  get 'ecommerce/ecommerce_product_view'
  get 'forum/forum_categories'
  get 'forum/forum_topics'
  get 'forum/forum_discussion'
  get 'pages/login'
  get 'pages/register'
  get 'pages/recover'
  get 'pages/lock'
  get 'pages/template'
  get 'pages/notfound'

  # api routes
  get '/api/documentation' => 'api#documentation'
  get '/api/datatable' => 'api#datatable'
  get '/api/jqgrid' => 'api#jqgrid'
  get '/api/jqgridtree' => 'api#jqgridtree'
  get '/api/i18n/:locale' => 'api#i18n'
  post '/api/xeditable' => 'api#xeditable'
  get '/api/xeditable-groups' => 'api#xeditablegroups'

  # the rest goes to root
  get '*path' => redirect('/')
end

app/models/ticket_flight.rb
class TicketFlight < ActiveRecord::Base

  belongs_to :person
  belongs_to :flight
  belongs_to :plane
  belongs_to :flight_type


  enum status: [ :Activo, :Deshabilitado, :Pago ]


  def self.search(query)
    if query.nil?
      return TicketFlight.all
    else
      return TicketFlight.joins(:plane, :flight, :flight_type).where('upper(flights.date) = ? or upper(planes.matricula) like ? or upper(flight_types.name_flight) like ?', "#{query}", "%#{query.upcase}%", "%#{query.upcase}%")
    end
  end


  def self.create_new(flight)
    if ["Comercial", "Comercial - Corto", "Comercial - Medio", "Comercial - Largo"].include?(flight.flight_type.name_flight)
      bill = TicketFlight.new
      bill.person = flight.pilot
      bill.flight = flight
      bill.plane = flight.plane
      bill.flight_type = flight.flight_type
      bill.price = bill.flight_type.price
      bill.km_start = flight.km_start
      bill.km_end = flight.km_end
      bill.time_fly = flight.time_fly
      bill.save
    else
      flight.people.each do |person|
        unless person.id == flight.pilot.id
          bill = TicketFlight.new
          bill.person = person
          bill.flight = flight
          bill.plane = flight.plane
          bill.flight_type = flight.flight_type
          bill.price = bill.flight_type.price
          bill.km_start = flight.km_start
          bill.km_end = flight.km_end
          bill.time_fly = flight.time_fly
          if !bill.save
            return false
          end
        end
      end
      return true
    end
  end
end

app/controllers/ticket_flights_controller.rb
class TicketFlightsController < ApplicationController

  layout 'application-h'


  def index
    #lleva vista
    if !params[:q].nil?
      @tickets = TicketFlight.search(params[:q]).order('created_at DESC')
    else
      @tickets = TicketFlight.all
    end
  end

  def deshabilitar
    @ticket = TicketFlight.find(params[:id])
    @ticket.status = 1
    @ticket.save
    redirect_to ticket_flights_path
  end

  def activar
    @ticket = TicketFlight.find(params[:id])
    @ticket.status = 0
    @ticket.save
    redirect_to ticket_flights_path
  end

  def create
    @ticket = TicketFlight.new (ticket_params)
    if @ticket.save
      flash[:success] = 'Factura creada correctamente.'
      redirect_to ticket_url(@ticket)
     else
      flash[:error] = 'Errores evitaron que se grabara la factura.'
      render 'new'
    end
  end

  def new
    #lleva vista
    @ticket =TicketFlight.new
  end

  def edit
    #lleva vista
    @ticket = TicketFlight.find(params[:id])
  end

  def show
    #lleva vista
    @ticket =TicketFlight.find(params[:id])
  end

  def update
    @ticket = TicketFlight.find(params[:id])
    if @ticket.update_attributes(ticket_params)
      flash[:success] = 'Factura Vuelo actualizado correctamente.'
      if (!ticket_params[:km_start].nil?)
        if TicketFlight.create_new(@ticket)
           @ticket.status = 2
           if @ticket.save
              redirect_to ticket_flights_url({q: @ticket.plane.name})
           end
        else
          flash[:error] = 'Errores evitaron que se finalizara la factura vuelo.'
          render 'finish'
        end
      else
        redirect_to ticket_flights_url(@ticket.id)
      end
    else
      flash[:error] = 'Errores evitaron que se grabara la factura vuelo.'
      render 'edit'
    end
  end
  
  def finish
   @ticket = TicketFlight.find(params[:id]) 
   @ticket.status = 2
   if @ticket.save
      redirect_to ticket_flights_url()
   
    else
      flash[:error] = 'Errores evitaron que se finalizara la factura vuelo.'
      redirect_to ticket_flights_url()
    end
  
  end

  def destroy
    Rails.logger.info "Eliminando factura"
      @ticket = TicketFlight.find(params[:id])
      if TicketFlight.custom_delete(@ticket)
        flash[:success] = 'factura deshabilitado correctamente.'
        redirect_to ticket_url
      else
        flash[:error] = 'Errores evitaron que se deshabilitara la factura.'
        render 'show'
      end
  end


  def deshabilitar
    @ticket = TicketFlight.find(params[:id])
    @ticket.status = 1
    @ticket.save
    redirect_to ticket_flight_path
  end

  def activar
    @ticket = Flight.find(params[:id])
    @ticket.status = 0
    @ticket.save
    redirect_to ticket_flight_path
  end


  private
    # Using a private method to encapsulate the permissible parameters is
    # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    def ticket_params
      params.require(:ticket_flight).permit(:flight_id, :person_id, :plane_id, :flight_type_id, :price, :status, :km_start, :km_end)
    end

end

app/views/ticket_flights/_form.html.erb
<!-- START panel-->
<div class="panel panel-default">

   <div class="panel-body">
      <%= form_for tickets_flights, html: {class: 'form-horizontal'} do |f| %>
         <div class="form-group">
            <label class="col-lg-2 control-label">Fecha</label>
            <div class="col-lg-10">
              <td width="65%"><strong><%= @ticket.flight.date %></strong>
            </div>
         </div>
         <div class="form-group">
            <label class="col-lg-2 control-label">Avion</label>
            <div class="col-lg-10">
             <%= f.select :plane_id, options_from_collection_for_select(Plane.all, :id, :name) %>
            </div>
         </div>
         <div class="form-group">
            <label class="col-lg-2 control-label">Tipo de vuelo</label>
            <div class="col-lg-10">
              <%= f.select :flight_type_id, options_from_collection_for_select(FlightType.all, :id, :name_flight) %>
             </div>
         </div>
         <div class="form-group">
            <label class="col-lg-2 control-label">Precio</label>
            <div class="col-lg-10">
              <%= f.text_field :price, placeholder: 'Precio', class: 'form-control' %>
            </div>
         </div>
                  <div class="form-group">
            <label class="col-lg-2 control-label">Kilometros de salida</label>
            <div class="col-lg-10">
              <%= f.text_field :km_start, placeholder: 'Kilometros salida', class: 'form-control' %>
            </div>
         </div>
                  <div class="form-group">
            <label class="col-lg-2 control-label">Kilometros de llegada</label>
            <div class="col-lg-10">
              <%= f.text_field :km_end, placeholder: 'Kilometros llegada', class: 'form-control' %>
            </div>
         </div>
         <div class="form-group">
            <label class="col-lg-2 control-label">Combustible cargado</label>
            <div class="col-lg-10">
              <td width="65%"><strong><%= @ticket.flight.fuel_charged %></strong>
            </div>
         </div>
         <div class="form-group">
            <label class="col-lg-2 control-label">Minutos volados</label>
            <div class="col-lg-10">
              <%= f.text_field :time_fly, placeholder: 'Minutos volados', class: 'form-control' %>
            </div>
         </div>
         <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
              <%= f.submit 'Guardar', class: 'btn btn-success'%>
            </div>
            <div class="col-lg-offset-2 col-lg-10">
              <%= link_to 'Volver', ticket_flights_path, class: 'btn btn-default' %>
            </div>
         </div>
      <% end %>
   </div>
</div>

app/views/ticket_flights/edit.html.erb
<h1>Editar la factura del vuelo</h1>

<%= render partial: 'form',locals: {tickets_flights: @ticket } %>

app/views/ticket_flights/index.html.erb
<div class="row">
   <div class="col-lg-12">
      <h3>Facturas
         <small>Listado de facturas de vuelos del sistema</small>
      </h3>

      <%= form_tag(ticket_flights_path, method: 'get') do  %>
        <%= text_field_tag :q,'',  placeholder: 'Busque por nombre tipo vuelo, matricula y fecha', :size => 46 %>
        <%= button_tag 'Buscar', type: 'submit',  class: 'btn btn-info btn-lg' %>
      <% end %>

   </div>
</div>
<!-- START row-->
<div class="row">
   <div class="col-lg-12">
      <!-- START panel-->
      <div class="panel panel-default">
         <div class="panel-body">
            <!-- START table-responsive-->
            <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                  <thead>
                     <tr>
                        <th>#</th>
                        <th>Fecha vuelo</th>
                        <th>Piloto</th>
                        <th>Avion</th>
                        <th>Matricula</th>
                        <th>Tipo de vuelo</th>
                        <th>Minutos volados</th>
                        <th>Precio</th>
                        <th>Estado</th>
                     </tr>
                  </thead>
                  <tbody>
                  <% @tickets.each do |ticket|%>
                     <tr>
                        <td><a href="<%= ticket_flight_path(ticket) %>">Ver</a>
                          <% if ticket.Activo? %>
                            /
                            
                            <%= link_to 'Pagar Vuelo', ticket_flights_finish_path(ticket.id), method: :put, data: { confirm: "Esta seguro?" } %>
                          <% end %>
                        </td>
                        <td><%= ticket.try(:flight).try(:date) %></td>
                        <td><%= ticket.try(:flight).try(:pilot).try(:complete_name) %></td>
                        <td><%= ticket.try(:plane).try(:name) %></td>
                        <td><%= ticket.try(:plane).try(:matricula) %></td>
                        <td><%= ticket.try(:flight_type).try(:name_flight) %></td>
                        <td><%= ticket.time_fly %> <span>minutos</span></td>
                        <td><%= ticket.price %></td>
                        <td><%= ticket.status %></td>
                     </tr>
                  <% end %>
                  </tbody>
               </table>
            </div>
            <!-- END table-responsive-->
            <div class='row actions' style='margin-top: 30px'>
              <div class='col-xs-10'>
                  <%= link_to 'Volver', root_path, class: 'btn btn-default' %>
              </div>
            </div>
         </div>
         
      </div>
      <!-- END panel-->
   </div>
   
</div>

app/views/ticket_flights/new.html.erb
new

app/views/ticket_flights/show.html.erb
<h3>Detalles de la factura</h3>

<div class="panel">
   <div class="panel-heading">Detalles de la factura vuelo</div>
   <table id="plane" style="clear: both" class="table table-bordered table-striped">
      <tbody>
         <tr>
            <td width="35%">Fecha vuelo</td>
            <td width="65%"><strong><%= @ticket.flight.date %></strong>
            </td>
         </tr>
         <tr>
            <td width="35%">Avion</td>
            <td width="65%"><strong><%= @ticket.plane.name %></strong>
            </td>
         </tr>
         <tr>
            <td width="35%">Tipo de vuelo</td>
            <td width="65%"><strong><%= @ticket.flight_type.name_flight %></strong>
            </td>
         </tr>
         <tr>
            <td width="35%">Precio</td>
            <td width="65%"><strong><%= @ticket.price %></strong>
            </td>
         </tr>
          <tr>
            <td width="35%">Km salida</td>
            <td width="65%"><strong><%= @ticket.flight.km_start %></strong>
            </td>
         </tr>
          <tr>
            <td width="35%">Km llegada</td>
            <td width="65%"><strong><%= @ticket.flight.km_end %></strong>
            </td>
         </tr>
         <tr>
            <td width="35%">Combustible cargado</td>
            <td width="65%"><strong><%= @ticket.flight.fuel_charged %></strong>
            </td>
         </tr>
         <tr>
            <td width="35%">Estado</td>
            <td width="65%"><strong><%= @ticket.status %></strong>
            </td>
         </tr>
      </tbody>
   </table>
</div>

<a href="<%= edit_ticket_flight_path(@ticket) %>" class='btn btn-success'>Modificar</a>
    <% if @ticket.Activo? %>
      <%= link_to 'Deshabilitar', ticket_flights_deshabilitar_path(@ticket.id), method: :put, data: {confirm: "Estas seguro que quiere deshabilitar?"}, class: 'btn btn-info' %>
    <% end %>
    <% if @ticket.Deshabilitado? %>
      <%= link_to 'Activar', ticket_flights_activar_path(@ticket.id), method: :put, data: {confirm: "Estas seguro que quiere activar?"}, class: 'btn btn-info' %>
    <% end %>
<%= link_to 'Volver', ticket_flights_path, class: 'btn btn-default' %>