config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # defaults to dashboard
  root :to => 'dashboard#dashboard_h'

  get 'fligths/search' => 'flights#search', as: :search_flights
  post 'flights/do_search' => "flights#do_search", as: :do_search_fligths
  get 'flights/:id/add_people' => 'flights#add_people', as: :flight_add_people
  post 'flights/:id/add_person/:person_id' => 'flights#add_person', as: :flight_add_person
  post 'flights/:id/remove_person/:person_id' => 'flights#remove_person', as: :flight_remove_person
  get 'flights/:id/finish' => 'flights#finish', as: :flight_finish
  
  get 'users/search' => 'users#search', as: :search_users
  post 'users/do_search' => "users#do_search", as: :do_search_users
  
  get 'planes/search' => 'planes#search', as: :search_planes
  post 'planes/do_search' => "planes#do_search", as: :do_search_planes

  get 'services/search' => 'services#search', as: :search_services
  post 'services/do_search' => "services#do_search", as: :do_search_services

  get 'flight_types/search' => 'flight_types#search', as: :search_flight_types
  post 'flight_types/do_search' => "flight_types#do_search", as: :do_search_flight_types

  get 'habilitation/:id' => 'pilot_habilitations#habilitation', as: :habilitation
  
  get 'users/recover' => 'users#recover', as: :recover
  post 'users/do_recover' => 'users#do_recover', as: :do_recover
    
  resources :planes
  resources :people
  resources :users
  resources :flights
  resources :ticket_flights
  resources :ticket_members
  resources :flight_types
  resources :services
  resources :pilot_habilitations
  resources :lists
  put 'flights/:id/deshabilitar' => 'flights#deshabilitar', as: :flight_deshabilitar
  put 'flights/:id/activar' => 'flights#activar', as: :flight_activar

  put 'ticket_flights/:id/deshabilitar' => 'ticket_flights#deshabilitar', as: :ticket_flights_deshabilitar
  put 'ticket_flights/:id/activar' => 'ticket_flights#activar', as: :ticket_flights_activar
  put 'ticket_flights/:id/finish' => 'ticket_flights#finish', as: :ticket_flights_finish

  put 'ticket_members/:id/finish' => 'ticket_members#finish', as: :ticket_members_finish
  
  get 'information/top_time' => 'lists#top_time', as: :top_time
  get 'information/people_with_debt' => 'lists#debt', as: :debt
  get 'information/monthly(/:year/:month)' => 'lists#monthly', as: :monthly



  # view routes
  get '/widgets' => 'widgets#index'
  get '/documentation' => 'documentation#index'

  get 'dashboard/dashboard_v1'
  get 'dashboard/dashboard_v2'
  get 'dashboard/dashboard_v3'
  get 'dashboard/dashboard_h'
  get 'elements/button'
  get 'elements/notification'
  get 'elements/spinner'
  get 'elements/animation'
  get 'elements/dropdown'
  get 'elements/nestable'
  get 'elements/sortable'
  get 'elements/panel'
  get 'elements/portlet'
  get 'elements/grid'
  get 'elements/gridmasonry'
  get 'elements/typography'
  get 'elements/fonticons'
  get 'elements/weathericons'
  get 'elements/colors'
  get 'elements/buttons'
  get 'elements/notifications'
  get 'elements/carousel'
  get 'forms/standard'
  get 'forms/extended'
  get 'forms/validation'
  get 'forms/wizard'
  get 'forms/upload'
  get 'forms/xeditable'
  get 'multilevel/level1'
  get 'multilevel/level3'
  get 'charts/flot'
  get 'charts/radial'
  get 'charts/chartjs'
  get 'charts/chartist'
  get 'charts/morris'
  get 'charts/rickshaw'
  get 'tables/standard'
  get 'tables/extended'
  get 'tables/datatable'
  get 'tables/jqgrid'
  get 'maps/google'
  get 'maps/vector'
  get 'extras/mailbox'
  get 'extras/timeline'
  get 'extras/calendar'
  get 'extras/invoice'
  get 'extras/search'
  get 'extras/todo'
  get 'extras/profile'
  get 'blog/blog'
  get 'blog/blog_post'
  get 'blog/blog_articles'
  get 'blog/blog_article_view'
  get 'ecommerce/ecommerce_orders'
  get 'ecommerce/ecommerce_order_view'
  get 'ecommerce/ecommerce_products'
  get 'ecommerce/ecommerce_product_view'
  get 'forum/forum_categories'
  get 'forum/forum_topics'
  get 'forum/forum_discussion'
  get 'pages/login'
  get 'pages/register'
  get 'pages/recover'
  get 'pages/lock'
  get 'pages/template'
  get 'pages/notfound'

  # api routes
  get '/api/documentation' => 'api#documentation'
  get '/api/datatable' => 'api#datatable'
  get '/api/jqgrid' => 'api#jqgrid'
  get '/api/jqgridtree' => 'api#jqgridtree'
  get '/api/i18n/:locale' => 'api#i18n'
  post '/api/xeditable' => 'api#xeditable'
  get '/api/xeditable-groups' => 'api#xeditablegroups'

  # the rest goes to root
  get '*path' => redirect('/')
end

app/controllers/flight_types_controller.rb
class FlightTypesController < ApplicationController


  layout 'application-h'

  def index
    #lleva vista
    if !params[:q].nil?
      @flight_types = FlightType.search(params[:q])
    else
      @flight_types = FlightType.all
    end
  end


  def create
    @flight_type = FlightType.new (flight_type_params)
    if @flight_type.save
      flash[:success] = 'Tipo de vuelo creado correctamente.'
      redirect_to flight_types_url(@flight_type)
    else
      flash[:error] = 'Errores evitaron que se grabara el tipo de vuelo.'
      render 'new'
    end
  end

  def new
    #lleva vista
    @flight_type = FlightType.new
  end

  def edit
    #lleva vista
    @flight_type = FlightType.find(params[:id])
  end

  def show
    #lleva vista
    @flight_type = FlightType.find(params[:id])
  end

  def update
    @flight_type = FlightType.find(params[:id])
    if @flight_type.update_attributes(flight_type_params)
      flash[:success] = 'Tipo de vuelo actualizado correctamente.'
      redirect_to flight_type_url(@flight_type.id)
    else
      flash[:error] = 'Errores evitaron que se grabara el tipo de vuelo.'
      render 'edit'
    end
  end

  def destroy
    Rails.logger.info "Eliminando tipo de vuelo"
    @flight_type = FlightType.find(params[:id])
    if FlightType.custom_delete(@flight_type)
      flash[:success] = 'Tipo de vuelo deshabilitado correctamente.'
      redirect_to flight_type_url
    else
      flash[:error] = 'Errores evitaron que se deshabilitara el tipo de vuelo.'
      render 'show'
    end
  end

  private
    # Using a private method to encapsulate the permissible parameters is
    # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    def flight_type_params
    params.require(:flight_type).permit(:name_flight, :description, :price, :status)
    end

end

app/helpers/flight_type_helper.rb
module FlightTypeHelper
end

app/views/flight_types/_form.html.erb
<h3>Crear nuevo tipo vuelo
   <small>Llene el formulario con los datos necesarios para crear un tipo de vuelo</small>
</h3>
<!-- START panel-->
<div class="panel panel-default">
   <div class="panel-heading">Crear tipo de vuelo</div>
   <div class="panel-body">
      <%= form_for flights_type, html: {class: 'form-horizontal'} do |f| %>
         <div class="form-group">
            <label class="col-lg-2 control-label">Nombre</label>
            <div class="col-lg-10">
             <%= f.text_field :name_flight, placeholder: 'Nombre del tipo vuelo', class: 'form-control', required:'required' %>
            </div>
         </div>
         <div class="form-group">
            <label class="col-lg-2 control-label">Descripcion</label>
            <div class="col-lg-10">
              <%= f.text_field :description, placeholder: 'Descripcion del tipo vuelo', class: 'form-control' %>
             </div>
         </div>
         <div class="form-group">
            <label class="col-lg-2 control-label">Costo</label>
            <div class="col-lg-10">
              <%= f.text_field :price, placeholder: 'Costo', class: 'form-control', required:'required' %>
            </div>
         </div>
         

         <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
         		<%= f.submit 'Guardar tipo vuelo', class: 'btn btn-success'%>
         		<% if flights_type.new_record? %>
         		  <%= link_to 'Volver', flight_types_path, class: 'btn btn-danger' %>
         		<% else %>
         		  <%= link_to 'Volver', flight_types_path(@flight_type), class: 'btn btn-danger' %>
         		<% end %>
         	</div>
         </div>
      <% end %>
   </div>
</div>

app/views/flight_types/edit.html.erb
<h1>Editar el tipo de vuelo</h1>

<%= render partial: 'form',locals: {flights_type: @flight_type } %>

app/views/flight_types/form.html.erb
_form_html

app/views/flight_types/index.html.erb
<div class="row">
   <div class="col-lg-12">
      <h3>Tipo de vuelos
         <small>Listado de tipo de vuelos del sistema</small>
      </h3>

      <%= form_tag(flight_types_path, method: 'get') do  %>
        <%= text_field_tag :q,'',  placeholder: 'Busque por nombre', :size => 40 %>
        <%= button_tag 'Buscar', type: 'submit',  class: 'btn btn-info btn-lg' %>
      <% end %>

   </div>
</div>
<!-- START row-->
<div class="row">
   <div class="col-lg-12">
      <!-- START panel-->
      <div class="panel panel-default">
         <div class="panel-body">
            <!-- START table-responsive-->
            <div class="table-responsive">
               <table class="table table-striped table-bordered table-hover">
                  <thead>
                     <tr>
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Descripcion</th>
                        <th>Precio</th>
                        <th>Estado</th>
                     </tr>
                  </thead>
                  <tbody>
                  <% @flight_types.each do |flight_type| %>
                     <tr>
                        <td><a href="<%= flight_type_path(flight_type) %>">Ver</a></td>
                        <td><%= flight_type.name_flight %></td>
                        <td><%= flight_type.description %></td>
                        <td><%= flight_type.price %></td>
                        <td>
                        <%= flight_type.status %>
                          
                        </td>
                     </tr>
                  <% end %>
                  </tbody>
               </table>
            </div>
            <!-- END table-responsive-->
            <div class='row actions' style='margin-top: 30px'>
              <div class='col-xs-10'>
                  <%= link_to 'Nuevo', new_flight_type_path, class: 'btn btn-success' %>
                  <%= link_to 'Volver', root_path, class: 'btn btn-default' %>
              </div>
            </div>
         </div>
         
      </div>
      <!-- END panel-->
   </div>
   
</div>

app/views/flight_types/new.html.erb
<h1>Guardar nuevo tipo vuelo</h1>

<%= render partial: 'form', locals: {flights_type: @flight_type} %>

app/views/flight_types/show.html.erb
<h3>Detalles de
   <small><%= @flight_type.name_flight %></small>
</h3>

<div class="">
   <div class="col-xs-6 panel">
     <div class="panel-heading">Detalles del tipo de vuelo</div>
     <table id="plane" style="clear: both" class="table table-bordered table-striped">
        <tbody>
           <tr>
              <td width="35%">Nombre</td>
              <td width="65%"><strong><%= @flight_type.name_flight %></strong>
              </td>
           </tr>
           <tr>
              <td width="35%">Descripcion</td>
              <td width="65%"><strong><%= @flight_type.description %></strong>
              </td>
           </tr>
           <tr>
              <td width="35%">Precio</td>
              <td width="65%"><strong><%= @flight_type.price %></strong>
              </td>
           </tr>
           <tr>
              <td width="35%">Estado</td>
              <td width="65%"><strong><%= @flight_type.status %></strong>

            </td>
           </tr>
        </tbody>
     </table>
     
     <a href="<%= edit_flight_type_path(@flight_type) %>" class='btn btn-success'>Modificar</a>

    <%= link_to 'Eliminar', @flight_type, method: :delete, data: {confirm: "Estas seguro que quiere eliminar?"}, class: 'btn btn-danger' %>
    <%= link_to 'Volver', flight_types_path, class: 'btn btn-default' %>
  </div>

<div class="row clearfix">
  <div class="col-xs-6 pull-left">
    
  </div>
  <div class="col-xs-3 pull-right">
   
  </div>
</div>