config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # defaults to dashboard
  root :to => 'dashboard#dashboard_h'

  get 'fligths/search' => 'flights#search', as: :search_flights
  post 'flights/do_search' => "flights#do_search", as: :do_search_fligths
  get 'flights/:id/add_people' => 'flights#add_people', as: :flight_add_people
  post 'flights/:id/add_person/:person_id' => 'flights#add_person', as: :flight_add_person
  post 'flights/:id/remove_person/:person_id' => 'flights#remove_person', as: :flight_remove_person
  get 'flights/:id/finish' => 'flights#finish', as: :flight_finish
  
  get 'users/search' => 'users#search', as: :search_users
  post 'users/do_search' => "users#do_search", as: :do_search_users
  
  get 'planes/search' => 'planes#search', as: :search_planes
  post 'planes/do_search' => "planes#do_search", as: :do_search_planes

  get 'services/search' => 'services#search', as: :search_services
  post 'services/do_search' => "services#do_search", as: :do_search_services

  get 'flight_types/search' => 'flight_types#search', as: :search_flight_types
  post 'flight_types/do_search' => "flight_types#do_search", as: :do_search_flight_types

  get 'habilitation/:id' => 'pilot_habilitations#habilitation', as: :habilitation
  
  get 'users/recover' => 'users#recover', as: :recover
  post 'users/do_recover' => 'users#do_recover', as: :do_recover
    
  resources :planes
  resources :people
  resources :users
  resources :flights
  resources :ticket_flights
  resources :ticket_members
  resources :flight_types
  resources :services
  resources :pilot_habilitations
  resources :lists
  put 'flights/:id/deshabilitar' => 'flights#deshabilitar', as: :flight_deshabilitar
  put 'flights/:id/activar' => 'flights#activar', as: :flight_activar

  put 'ticket_flights/:id/deshabilitar' => 'ticket_flights#deshabilitar', as: :ticket_flights_deshabilitar
  put 'ticket_flights/:id/activar' => 'ticket_flights#activar', as: :ticket_flights_activar
  put 'ticket_flights/:id/finish' => 'ticket_flights#finish', as: :ticket_flights_finish

  put 'ticket_members/:id/finish' => 'ticket_members#finish', as: :ticket_members_finish
  
  get 'information/top_time' => 'lists#top_time', as: :top_time
  get 'information/people_with_debt' => 'lists#debt', as: :debt
  get 'information/monthly(/:year/:month)' => 'lists#monthly', as: :monthly



  # view routes
  get '/widgets' => 'widgets#index'
  get '/documentation' => 'documentation#index'

  get 'dashboard/dashboard_v1'
  get 'dashboard/dashboard_v2'
  get 'dashboard/dashboard_v3'
  get 'dashboard/dashboard_h'
  get 'elements/button'
  get 'elements/notification'
  get 'elements/spinner'
  get 'elements/animation'
  get 'elements/dropdown'
  get 'elements/nestable'
  get 'elements/sortable'
  get 'elements/panel'
  get 'elements/portlet'
  get 'elements/grid'
  get 'elements/gridmasonry'
  get 'elements/typography'
  get 'elements/fonticons'
  get 'elements/weathericons'
  get 'elements/colors'
  get 'elements/buttons'
  get 'elements/notifications'
  get 'elements/carousel'
  get 'forms/standard'
  get 'forms/extended'
  get 'forms/validation'
  get 'forms/wizard'
  get 'forms/upload'
  get 'forms/xeditable'
  get 'multilevel/level1'
  get 'multilevel/level3'
  get 'charts/flot'
  get 'charts/radial'
  get 'charts/chartjs'
  get 'charts/chartist'
  get 'charts/morris'
  get 'charts/rickshaw'
  get 'tables/standard'
  get 'tables/extended'
  get 'tables/datatable'
  get 'tables/jqgrid'
  get 'maps/google'
  get 'maps/vector'
  get 'extras/mailbox'
  get 'extras/timeline'
  get 'extras/calendar'
  get 'extras/invoice'
  get 'extras/search'
  get 'extras/todo'
  get 'extras/profile'
  get 'blog/blog'
  get 'blog/blog_post'
  get 'blog/blog_articles'
  get 'blog/blog_article_view'
  get 'ecommerce/ecommerce_orders'
  get 'ecommerce/ecommerce_order_view'
  get 'ecommerce/ecommerce_products'
  get 'ecommerce/ecommerce_product_view'
  get 'forum/forum_categories'
  get 'forum/forum_topics'
  get 'forum/forum_discussion'
  get 'pages/login'
  get 'pages/register'
  get 'pages/recover'
  get 'pages/lock'
  get 'pages/template'
  get 'pages/notfound'

  # api routes
  get '/api/documentation' => 'api#documentation'
  get '/api/datatable' => 'api#datatable'
  get '/api/jqgrid' => 'api#jqgrid'
  get '/api/jqgridtree' => 'api#jqgridtree'
  get '/api/i18n/:locale' => 'api#i18n'
  post '/api/xeditable' => 'api#xeditable'
  get '/api/xeditable-groups' => 'api#xeditablegroups'

  # the rest goes to root
  get '*path' => redirect('/')
end

app/views/layouts/partials/_footer.html.erb
<span>&copy; 2015 - AeroClub</span>

app/views/layouts/partials/_topnavbar.html.erb
<!-- START Top Navbar-->
<nav role="navigation" class="navbar topnavbar">
   <!-- START navbar header-->
   <div class="navbar-header">
      <a href="#/" class="navbar-brand">
         <div class="brand-logo">
            <img src="<%= image_path('angle/logo.png') %>" alt="App Logo" class="img-responsive" />
         </div>
         <div class="brand-logo-collapsed">
            <img src="<%= image_path('angle/logo-single.png') %>" alt="App Logo" class="img-responsive" />
         </div>
      </a>
   </div>
   <!-- END navbar header-->
   <!-- START Nav wrapper-->
   <div class="nav-wrapper">
      <!-- START Left navbar-->
      <ul class="nav navbar-nav">
         <li>
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <a href="#" data-toggle-state="aside-collapsed" class="hidden-xs">
               <em class="fa fa-navicon"></em>
            </a>
            <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
            <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
               <em class="fa fa-navicon"></em>
            </a>
         </li>
         <!-- START User avatar toggle-->
         <li>
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <a id="user-block-toggle" href="#user-block" data-toggle="collapse">
               <em class="icon-user"></em>
            </a>
         </li>
         <!-- END User avatar toggle-->
         <!-- START lock screen-->
         <li>
            <a href="/pages/lock" title="Lock screen">
               <em class="icon-lock"></em>
            </a>
         </li>
         <!-- END lock screen-->
      </ul>
      <!-- END Left navbar-->
      <!-- START Right Navbar-->
      <ul class="nav navbar-nav navbar-right">
         <!-- Search icon-->
         <li>
            <a href="#" data-search-open="">
               <em class="icon-magnifier"></em>
            </a>
         </li>
         <!-- Fullscreen (only desktops)-->
         <li class="visible-lg">
            <a href="#" data-toggle-fullscreen="">
               <em class="fa fa-expand"></em>
            </a>
         </li>
         <!-- START Alert menu-->
         <li class="dropdown dropdown-list">
            <a href="#" data-toggle="dropdown">
               <em class="icon-bell"></em>
               <div class="label label-danger">11</div>
            </a>
            <!-- START Dropdown menu-->
            <ul class="dropdown-menu animated flipInX">
               <li>
                  <!-- START list group-->
                  <div class="list-group">
                     <!-- list item-->
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-twitter fa-2x text-info"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">New followers</p>
                              <p class="m0 text-muted">
                                 <small>1 new follower</small>
                              </p>
                           </div>
                        </div>
                     </a>
                     <!-- list item-->
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-envelope fa-2x text-warning"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">New e-mails</p>
                              <p class="m0 text-muted">
                                 <small>You have 10 new emails</small>
                              </p>
                           </div>
                        </div>
                     </a>
                     <!-- list item-->
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-tasks fa-2x text-success"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">Pending Tasks</p>
                              <p class="m0 text-muted">
                                 <small>11 pending task</small>
                              </p>
                           </div>
                        </div>
                     </a>
                     <!-- last list item -->
                     <a href="#" class="list-group-item">
                        <small>More notifications</small>
                        <span class="label label-danger pull-right">14</span>
                     </a>
                  </div>
                  <!-- END list group-->
               </li>
            </ul>
            <!-- END Dropdown menu-->
         </li>
         <!-- END Alert menu-->
         <!-- START Contacts button-->
         <li>
            <a href="#" data-toggle-state="offsidebar-open" data-no-persist="true">
               <em class="icon-notebook"></em>
            </a>
         </li>
         <!-- END Contacts menu-->
      </ul>
      <!-- END Right Navbar-->
   </div>
   <!-- END Nav wrapper-->
   <!-- START Search form-->
   <form role="search" action="search.html" class="navbar-form">
      <div class="form-group has-feedback">
         <input type="text" placeholder="Type and hit enter ..." class="form-control" />
         <div data-search-dismiss="" class="fa fa-times form-control-feedback"></div>
      </div>
      <button type="submit" class="hidden btn btn-default">Submit</button>
   </form>
   <!-- END Search form-->
</nav>
<!-- END Top Navbar-->

app/views/layouts/partials/_topnavbar_h.html.erb
<!-- START Top Navbar-->
<nav role="navigation" class="navbar topnavbar">
   <!-- START navbar header-->
   <div class="navbar-header">
      <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-toggle">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
      </button>
      <a href="#/" class="navbar-brand">
         <div class="brand-logo">
            <img src="<%= image_path('angle/aeroclub.jpg') %>" alt="App Logo" width="100" height="50" class="img-responsive" />
         </div>
         <div class="brand-logo-collapsed">
            <img src="<%= image_path('angle/aeroclub.jpg') %>" alt="App Logo" class="img-responsive" />
         </div>
      </a>
   </div>
   <!-- END navbar header-->
   <!-- START Nav wrapper-->
   <div class="navbar-collapse collapse">
      <!-- START Left navbar-->
      <ul class="nav navbar-nav">
         <li><a href="/">Inicio</a></li>
         <li><a href="<%= flights_path %>">Vuelos</a></li>
         <li><a href="<%= flight_types_path %>">Tipos de vuelo</a></li>
         <li><a href="<%= planes_path %>">Aviones</a></li>
         <li><a href="<%= people_path %>">Personas</a></li>
         <li><a href="<%= ticket_members_path %>">Facturas socios</a></li>
         <li><a href="<%= ticket_flights_path %>">Facturas vuelos</a></li>
         <li><a href="<%= services_path %>">Services</a></li>
          <% if current_user.try(:Presidente?) %>
           <li><a href="<%= lists_path %>">Listados</a></li>
           <li><a href="<%= users_path %>">Usuarios</a></li>
          <% end %>
      </ul>
      <!-- END Left navbar-->
      <!-- START Right Navbar-->
      <ul class="nav navbar-nav navbar-right">
         <!-- START lock screen-->
         <li>
            <%= link_to(destroy_user_session_path, :method => :delete) do %>
               <em class="icon-lock"></em>
            <% end %>
         </li>
         
      </ul>
      <!-- END Right Navbar-->
   </div>
   <!-- END Nav wrapper-->
   <!-- START Search form-->
   <form role="search" action="search.html" class="navbar-form">
      <div class="form-group has-feedback">
         <input type="text" placeholder="Ingrese una nueva busqueda..." class="form-control" />
         <div data-search-dismiss="" class="fa fa-times form-control-feedback"></div>
      </div>
      <button type="submit" class="hidden btn btn-default">Enviar</button>
   </form>
   <!-- END Search form-->
</nav>
<!-- END Top Navbar-->